import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-suggestions-component',
  templateUrl: './suggestions-component.component.html',
  styleUrls: ['./suggestions-component.component.css']
})
export class SuggestionsComponentComponent implements OnInit {
  product1:any={
    "index_num": 418,
    "mobiles": "OnePlus 8 Pro",
    "Link": "https://gadgets.ndtv.com/oneplus-8-pro-price-in-india-91433",
    "img_links": "https://i.gadgets360cdn.com/products/large/oneplus-8-pro-375x800-1586878860.jpg",
    "best_buy_links": "https://pricee.com/api/redirect/t.php?utm_source=PRICE-IN-INDIA&itemid=2-b078bn2h3r&pgtyp=product&pgcat=Mobiles",
    "Summary": "The OnePlus 8 Pro has a similar design as the OnePlus 8 but with some subtle changes. Its display is actually rounded on the sides, rather than just having curved glass like on the 8. It �has a pretty big 6.78-inch QHD+ (1440x3168-pixel) AMOLED panel, with a claimed high colour accuracy and HDR10+ support. New this year is the 120Hz refresh rate. �The display is vibrant, colourful, and bright.",
    "k_Display": "6.78-inch (1440x3168)",
    "k_Processor": "Qualcomm Snapdragon 865",
    "k_Front_Camera": "16MP",
    "k_Rear_Camera": "48MP + 8MP + 48MP + 5MP",
    "k_RAM": "8GB",
    "k_Storage": "128GB",
    "k_Battery_Capacity": "4510mAh",
    "k_OS": "Android 10",
    "design": 9,
    "display": 10,
    "software": 10,
    "performance": 10,
    "battery_life": 10,
    "camera": 9,
    "value_for_money": 9,
    "b_Price": 48999,
    "Alternate_names": null,
    "Brand": "OnePlus",
    "Model": "8 Pro",
    "Price_in_India": "59,999",
    "Release_date": "14th April 2020",
    "Launched_in_India": "No",
    "Form_factor": "Touchscreen",
    "Thickness": null,
    "Body_type": "Glass",
    "Dimensions_mm": "165.30 x 74.35 x 8.50",
    "Weight": "199",
    "IP_rating": "IP68",
    "Battery_capacity_mAh": "4510",
    "Removable_battery": "No",
    "Fast_charging": "Proprietary",
    "Wireless_charging": "Yes",
    "Colours": "Glacial Green, Onyx Black, Ultramarine Blue",
    "SAR_value": null,
    "Refresh_Rate": null,
    "Screen_size_inches": 6.78,
    "Touchscreen": "Yes",
    "Resolution": "1440x3168 pixels",
    "Protection_type": "Gorilla Glass",
    "Aspect_ratio": "19.8:9",
    "Pixels_per_inch_PPI": 513,
    "Processor": "octa-core",
    "Processor_make": "Qualcomm Snapdragon 865",
    "RAM": "8GB",
    "Internal_storage": "128GB",
    "Expandable_storage": "No",
    "Expandable_storage_type": null,
    "Expandable_storage_up_to_GB": null,
    "Dedicated_microSD_slot": null,
    "Rear_camera": "48-megapixel (f/1.78, 1.12-micron) + 8-megapixel (f/2.44, 1.0-micron) + 48-megapixel (f/2.2) + 5-megapixel (f/2.4)",
    "No_of_Rear_Cameras": null,
    "Rear_autofocus": "Yes",
    "Rear_flash": "Dual LED",
    "Front_camera": "16-megapixel (f/2.45, 1.0-micron)",
    "No_of_Front_Cameras": null,
    "Front_autofocus": "No",
    "Front_flash": null,
    "PopUp_Camera": null,
    "Operating_system": "Android 10",
    "Skin": "OxygenOS",
    "Face_unlock": "Yes",
    "3D_face_recognition": null,
    "Fingerprint_sensor": "Yes",
    "InDisplay_Fingerprint_Sensor": "Yes",
    "Compass_Magnetometer": "Yes",
    "Proximity_sensor": "Yes",
    "Accelerometer": "Yes",
    "Ambient_light_sensor": "Yes",
    "Gyroscope": "Yes",
    "Barometer": null,
    "Temperature_sensor": null,
    "WiFi": "Yes",
    "WiFi_standards_supported": "802.11 a/b/g/n/ac/ax",
    "GPS": "Yes",
    "Bluetooth": "Yes, v 5.10",
    "NFC": "Yes",
    "Infrared": null,
    "USB_OTG": null,
    "USB_TypeC": "Yes",
    "MicroUSB": null,
    "Lightning": null,
    "Headphones": null,
    "FM": null,
    "Number_of_SIMs": 2,
    "WiFi_Direct": null,
    "Mobile_HighDefinition_Link_MHL": null,
    "Active_4G_on_both_SIM_cards": null,
    "SIM_1_SIM_Type": "Nano-SIM",
    "GSMCDMA": "GSM",
    "3G": "Yes",
    "4G_LTE": "Yes",
    "5G": "Yes",
    "Supports_4G_in_India_Band_40": "Yes",
    "SIM_2_SIM_Type": "Nano-SIM",
    "Pros": "Excellent build quality, IP68 rating ;Bright, fluid display ;Very good rear cameras ;Solid overall performance ;Great battery life ;Fast wireless charging",
    "Cons": "Selfie camera could be better ;Excessive rear camera bulge",
    "Design_diff": 0,
    "Display_diff": 2,
    "Software_diff": 3,
    "Performance_diff": 0,
    "Battery_diff": 10,
    "Camera_diff": 0,
    "main_diff": 15
}
product2:any={
  "index_num": 112,
  "mobiles": "Google Pixel XL",
  "Link": "https://gadgets.ndtv.com/google-pixel-xl-3812",
  "img_links": "https://drop.ndtv.com/TECH/product_database/images/480x960_2_3812_480X960_1028201654557PM.jpg",
  "best_buy_links": "https://pricee.com/api/redirect/t.php?utm_source=PRICE-IN-INDIA&itemid=1-mrff5ptqchdbzudf&pgtyp=product&pgcat=Mobiles",
  "Summary": "Google is embarking on a new adventure with its first self-designed smartphones, the Pixel and Pixel XL, which are practically identical other than their size. While its looks aren't going to set the world on fire, the Pixel XL is packed with today's top components including a Snapdragon 821 SoC and 4GB of RAM. Software, including the new voice-based Google Assistant, is the main draw. The company also boasts of having developed the best smartphone camera in the world, and we can see why. Go for the Pixel or Pixel XL if you want Google's purest vision of what Android should be, but be prepared to pay a lot for that privilege.",
  "k_Display": "5.50-inch (1440x2560)",
  "k_Processor": "Qualcomm Snapdragon 821",
  "k_Front_Camera": "8MP",
  "k_Rear_Camera": "12.3MP",
  "k_RAM": "4GB",
  "k_Storage": "32GB",
  "k_Battery_Capacity": "3450mAh",
  "k_OS": "Android 7.1",
  "design": 8,
  "display": 10,
  "software": 9,
  "performance": 10,
  "battery_life": 9,
  "camera": 10,
  "value_for_money": 8,
  "b_Price": 6999,
  "Alternate_names": null,
  "Brand": "Google",
  "Model": "Pixel XL",
  "Price_in_India": "24,000",
  "Release_date": "Oct-16",
  "Launched_in_India": null,
  "Form_factor": "Touchscreen",
  "Thickness": null,
  "Body_type": null,
  "Dimensions_mm": "154.70 x 75.70 x 8.50",
  "Weight": "168",
  "IP_rating": null,
  "Battery_capacity_mAh": "3450",
  "Removable_battery": "No",
  "Fast_charging": null,
  "Wireless_charging": null,
  "Colours": "Blue, Quite Black, Very Silver",
  "SAR_value": 0.46,
  "Refresh_Rate": null,
  "Screen_size_inches": 5.5,
  "Touchscreen": "Yes",
  "Resolution": "1440x2560 pixels",
  "Protection_type": null,
  "Aspect_ratio": null,
  "Pixels_per_inch_PPI": 534,
  "Processor": "1.6GHz quad-core",
  "Processor_make": "Qualcomm Snapdragon 821",
  "RAM": "4GB",
  "Internal_storage": "32GB",
  "Expandable_storage": "No",
  "Expandable_storage_type": null,
  "Expandable_storage_up_to_GB": null,
  "Dedicated_microSD_slot": null,
  "Rear_camera": "12.3-megapixel",
  "No_of_Rear_Cameras": null,
  "Rear_autofocus": null,
  "Rear_flash": "Dual LED",
  "Front_camera": "8-megapixel",
  "No_of_Front_Cameras": null,
  "Front_autofocus": null,
  "Front_flash": null,
  "PopUp_Camera": null,
  "Operating_system": "Android 7.1",
  "Skin": "Pixel Launcher",
  "Face_unlock": null,
  "3D_face_recognition": null,
  "Fingerprint_sensor": null,
  "InDisplay_Fingerprint_Sensor": null,
  "Compass_Magnetometer": "Yes",
  "Proximity_sensor": "Yes",
  "Accelerometer": "Yes",
  "Ambient_light_sensor": "Yes",
  "Gyroscope": "Yes",
  "Barometer": "Yes",
  "Temperature_sensor": "No",
  "WiFi": "Yes",
  "WiFi_standards_supported": "802.11 g/n/ac",
  "GPS": "Yes",
  "Bluetooth": "Yes, v 4.20",
  "NFC": "Yes",
  "Infrared": "No",
  "USB_OTG": "Yes",
  "USB_TypeC": null,
  "MicroUSB": null,
  "Lightning": null,
  "Headphones": "3.5mm",
  "FM": "No",
  "Number_of_SIMs": 1,
  "WiFi_Direct": "No",
  "Mobile_HighDefinition_Link_MHL": "No",
  "Active_4G_on_both_SIM_cards": null,
  "SIM_1_SIM_Type": null,
  "GSMCDMA": "GSM",
  "3G": "Yes",
  "4G_LTE": "Yes",
  "5G": null,
  "Supports_4G_in_India_Band_40": "Yes",
  "SIM_2_SIM_Type": null,
  "Pros": "Brilliant low-light photography ;Fast modern processor ;Great battery life ;Google Assistant with localisations for India",
  "Cons": "Not very stylish or eye-catching ;Expensive ;No storage expansion",
  "Design_diff": -1,
  "Display_diff": 2,
  "Software_diff": 0,
  "Performance_diff": 0,
  "Battery_diff": 5,
  "Camera_diff": 6,
  "main_diff": 12
}
key_specs_keys=['Display','Processor','Front Camera','Rear Camera','RAM','Storage','Battery','OS'];
key_specs_values1:any[]=[];
key_specs_values2:any[]=[];
counter(i: number) {
  return new Array(i);
}


  constructor() { }

  ngOnInit(): void {
    for(let key of this.key_specs_keys)
    {
      key = key.split(' ').join('_');
      key = 'k_'+key;
      //console.log(key);
      this.key_specs_values1.push(this.product1[key]);
    }
    for(let key of this.key_specs_keys)
    {
      key = key.split(' ').join('_');
      key = 'k_'+key;
      //console.log(key);
      this.key_specs_values2.push(this.product2[key]);
    }
  }

}
